version: 0.2

phases:
  install:  
    commands:
      - echo "installing prerequisites"
      - chmod -R 777 \$PWD/*
      - echo $(scripts/install.sh)
  build:
    commands:
      - echo "terraform destroy"
      - echo $(terraform destroy -auto-approve -var AWS_SECRET_KEY=${SecretKey} -var AWS_ACCESS_KEY=${AccessKey})