variable "AWS_REGION" { default = "ap-south-1"}
variable "AWS_SECRET_KEY" {}
variable "AWS_ACCESS_KEY" {}
variable "CREATE_ACCOUNT_LAMBDA_RUN_TIME" {}
variable "CREATE_ACCOUNT_LAMBDA_HANDLER" {}
variable "CREATE_ACCOUNT_SOURCE_FILE_NAME" {}
variable "CREATE_ACCOUNT_SOURCE_FILE_PATH" {}

variable "ACTIVATE_ACCOUNT_LAMBDA_RUN_TIME" {}
variable "ACTIVATE_ACCOUNT_LAMBDA_HANDLER" {}
variable "ACTIVATE_ACCOUNT_SOURCE_FILE_NAME" {}
variable "ACTIVATE_ACCOUNT_SOURCE_FILE_PATH" {}

variable "ADMIN_EMAIL" {}
